local H = require('tests.helpers')
local config = require('nvim-tex.config')
local surround = require('nvim-tex.surround')

describe('surround', function()
  before_each(H.need_parser)
  after_each(H.cleanup)

  describe('environments', function()
    local ENV = {
      '\\begin{itemize}',
      '  \\item one',
      '\\end{itemize}',
    }

    it('dse removes the \\begin and \\end lines', function()
      H.buf(ENV)
      H.cursor_at('one')
      surround.env_delete()
      T.eq({ '  \\item one' }, H.lines())
    end)

    it('cse renames both ends', function()
      H.buf(ENV)
      H.cursor_at('one')
      surround.env_change('enumerate')
      T.eq({ '\\begin{enumerate}', '  \\item one', '\\end{enumerate}' }, H.lines())
    end)

    it('tss adds and removes the star', function()
      H.buf({ '\\begin{align}', 'a &= b', '\\end{align}' })
      H.cursor_at('a &= b')
      surround.env_toggle_star()
      T.eq('\\begin{align*}', H.lines()[1])
      T.eq('\\end{align*}', H.lines()[3])

      surround.env_toggle_star()
      T.eq('\\begin{align}', H.lines()[1])
    end)

    it('tse walks the configured cycle', function()
      H.buf(ENV)
      H.cursor_at('one')
      surround.env_toggle()
      T.eq('\\begin{enumerate}', H.lines()[1])
      surround.env_toggle()
      T.eq('\\begin{description}', H.lines()[1])
    end)

    it('tse carries the star over', function()
      H.buf({ '\\begin{align*}', 'a &= b', '\\end{align*}' })
      H.cursor_at('a &= b')
      surround.env_toggle()
      T.eq('\\begin{gather*}', H.lines()[1])
    end)

    it('tse says so when there is no target', function()
      H.buf({ '\\begin{center}', 'text', '\\end{center}' })
      H.cursor_at('text')
      surround.env_toggle()
      T.ok(H.notified('no toggle target'))
      T.eq('\\begin{center}', H.lines()[1])
    end)

    it('complains outside an environment', function()
      H.buf({ 'just prose' })
      H.cursor_at('prose')
      surround.env_delete()
      T.ok(H.notified('no surrounding environment'))
    end)
  end)

  describe('math zones', function()
    it('ds$ drops the dollars', function()
      H.buf({ 'text $a + b$ text' })
      H.cursor_at('a + b')
      surround.math_delete()
      T.eq({ 'text a + b text' }, H.lines())
    end)

    it('ts$ turns inline math into a display block on its own lines', function()
      H.buf({ 'text $a + b$ text' })
      H.cursor_at('a + b')
      surround.math_toggle()
      T.eq({ 'text \\[', '  a + b', '\\] text' }, H.lines())
    end)

    it('ts$ turns a display block back into inline math', function()
      H.buf({ 'text \\[a + b\\] text' })
      H.cursor_at('a + b')
      surround.math_toggle()
      T.eq({ 'text $a + b$ text' }, H.lines())
    end)

    it('complains outside a math zone', function()
      H.buf({ 'just prose' })
      H.cursor_at('prose')
      surround.math_delete()
      T.ok(H.notified('not inside a math zone'))
    end)
  end)

  describe('commands', function()
    it('dsc unwraps the command, keeping its argument', function()
      H.buf({ 'a \\textbf{bold} b' })
      H.cursor_at('bold')
      surround.cmd_delete()
      T.eq({ 'a bold b' }, H.lines())
    end)

    it('csc renames it', function()
      H.buf({ 'a \\textbf{bold} b' })
      H.cursor_at('bold')
      surround.cmd_change('emph')
      T.eq({ 'a \\emph{bold} b' }, H.lines())
    end)

    it('tsc adds and removes the star', function()
      H.buf({ '\\section{One}' })
      H.cursor_at('One')
      surround.cmd_toggle_star()
      T.eq({ '\\section*{One}' }, H.lines())
      surround.cmd_toggle_star()
      T.eq({ '\\section{One}' }, H.lines())
    end)

    it('tsc honours edit.toggle_star_cmds', function()
      config.setup({ edit = { toggle_star_cmds = { 'section' } } })
      H.buf({ '\\textbf{bold}' })
      H.cursor_at('bold')
      surround.cmd_toggle_star()
      T.eq({ '\\textbf{bold}' }, H.lines())
      T.ok(H.notified('toggle_star_cmds'))
    end)

    it('tsb toggles the trailing line break', function()
      H.buf({ 'a &= b' })
      H.cursor(1, 0)
      surround.cmd_toggle_break()
      T.eq({ 'a &= b \\\\' }, H.lines())
      surround.cmd_toggle_break()
      T.eq({ 'a &= b' }, H.lines())
    end)
  end)

  describe('fractions', function()
    it('tsf unwraps \\frac into a slash', function()
      H.buf({ '$\\frac{a}{b}$' })
      H.cursor_at('a}')
      surround.toggle_fraction(false)
      T.eq({ '$a/b$' }, H.lines())
    end)

    it('tsf wraps a slash back into \\frac', function()
      H.buf({ '$a/b$' })
      H.cursor_at('/')
      surround.toggle_fraction(false)
      T.eq({ '$\\frac{a}{b}$' }, H.lines())
    end)
  end)

  describe('delimiters', function()
    it('dsd removes the braces', function()
      H.buf({ '\\textbf{bold}' })
      H.cursor_at('bold')
      surround.delim_delete()
      T.eq({ '\\textbfbold' }, H.lines())
    end)

    it('dsd takes \\left and \\right with it', function()
      H.buf({ '$\\left( x \\right)$' })
      H.cursor_at('x ')
      surround.delim_delete()
      T.eq({ '$ x $' }, H.lines())
    end)

    it('tsd adds \\left and \\right', function()
      H.buf({ '$(x)$' })
      H.cursor_at('x')
      surround.delim_toggle_modifier(false)
      T.eq({ '$\\left(x\\right)$' }, H.lines())
    end)

    it('tsd takes them off again', function()
      H.buf({ '$\\left(x\\right)$' })
      H.cursor_at('x\\')
      surround.delim_toggle_modifier(false)
      T.eq({ '$(x)$' }, H.lines())
    end)

    it('complains when there is no delimiter', function()
      H.buf({ 'just prose' })
      H.cursor_at('prose')
      surround.delim_delete()
      T.ok(H.notified('no surrounding delimiter'))
    end)
  end)

  describe('surrounding', function()
    --- The wrapped lines are re-indented with `==`, so the comparison ignores
    --- leading whitespace: how much of it there is depends on the indent
    --- settings, not on this plugin.
    ---@return string[]
    local function trimmed()
      return vim.tbl_map(vim.trim, H.lines())
    end

    it('wraps a range of lines in an environment', function()
      H.buf({ 'one', 'two', 'three' })
      surround.env_surround_lines(1, 2, 'center')
      T.eq({ '\\begin{center}', 'one', 'two', '\\end{center}', 'three' }, trimmed())
    end)

    it('wraps a single line', function()
      H.buf({ 'one' })
      surround.env_surround_lines(1, 1, 'equation')
      T.eq({ '\\begin{equation}', 'one', '\\end{equation}' }, trimmed())
    end)
  end)

  describe(']] in insert mode', function()
    -- The mapping runs with the cursor where insert mode puts it, which may
    -- be one past the last character. Normal mode would clamp it back.
    before_each(function()
      vim.o.virtualedit = 'onemore'
    end)

    after_each(function()
      vim.o.virtualedit = ''
    end)

    it('closes the innermost open environment on a new line after the cursor', function()
      H.buf({ '\\begin{itemize}', '  \\item one' })
      H.cursor(2, #'  \\item one')
      surround.delim_close()
      T.eq({ '\\begin{itemize}', '  \\item one', '\\end{itemize}' }, H.lines())
      T.eq({ 3, #'\\end{itemize}' }, vim.api.nvim_win_get_cursor(0))
    end)

    it('reuses a blank line and aligns with the \\begin', function()
      H.buf({ '  \\begin{itemize}', '    \\item one', '    ' })
      H.cursor(3, 4)
      surround.delim_close()
      T.eq({ '  \\begin{itemize}', '    \\item one', '  \\end{itemize}' }, H.lines())
      T.eq({ 3, #'  \\end{itemize}' }, vim.api.nvim_win_get_cursor(0))
    end)

    it('keeps text after the cursor behind the \\end', function()
      H.buf({ '\\begin{center}', 'text rest' })
      H.cursor(2, #'text ')
      surround.delim_close()
      T.eq({ '\\begin{center}', 'text ', '\\end{center}rest' }, H.lines())
    end)

    it('closes an open \\left with the matching \\right', function()
      H.buf({ '$\\left( x' })
      H.cursor(1, #'$\\left( x')
      surround.delim_close()
      T.eq({ '$\\left( x\\right)' }, H.lines())
    end)

    it('closes a plain brace', function()
      H.buf({ '\\textbf{bold' })
      H.cursor(1, #'\\textbf{bold')
      surround.delim_close()
      T.eq({ '\\textbf{bold}' }, H.lines())
    end)

    it('leaves the document environment alone', function()
      H.buf({ '\\begin{document}', 'text' })
      H.cursor(2, 4)
      surround.delim_close()
      T.eq({ '\\begin{document}', 'text' }, H.lines())
    end)
  end)
end)
